{% set name = "pystardb" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyStarDB-{{ version }}.tar.gz
  sha256: 95d28bc71b87f81875c4876498e4761543166e85f33b5047313829eb717ddf65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.14.5
    - pandas >=1.0.5
    - python >={{ python_min }}

test:
  imports:
    - pyStarDB
    - pyStarDB.sp_pystardb
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MPI-Dortmund/pyStarDB
  summary: Star file python Package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - mstabrin
    - thorstenwagner
